# Generated by Django 5.0.7 on 2024-08-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=550, verbose_name='Title')),
                ('owner', models.CharField(max_length=250, verbose_name='Owner')),
                ('datenow', models.DateField(verbose_name='Published')),
                ('c_name', models.CharField(max_length=2048, verbose_name='Enter certificate name')),
                ('file_name', models.CharField(max_length=550, verbose_name='File name')),
                ('articlesnumber', models.CharField(max_length=1024, verbose_name='Articles number')),
                ('certificate_file', models.FileField(upload_to='certificates/', verbose_name='Certificate')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
